name: Daily Unity Job Check
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # This environment variable opts you into Node 24 immediately
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Keep an eye out for v5

      - name: Set up Python
        uses: actions/setup-python@v5 # Keep an eye out for v6

      - name: Install dependencies
        run: pip install python-jobspy requests pandas feedparser

      - name: Run job check
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py